#pragma once

#include <map>
#include <string>

namespace T6
{
    namespace BSPFlags
    {
        const std::map<int, std::string> contentFlags_FlagToName = {
            {1,          "solid"       },
            {2,          "foliage"     },
            {4,          "unknown_c1"  },
            {8,          "unknown_c2"  },
            {0x10,       "transparent" },
            {0x20,       "water"       },
            {0x40,       "canshootclip"},
            {0x80,       "clipmissile" },
            {0x100,      "unknown_c3"  },
            {0x200,      "vehicleclip" },
            {0x400,      "itemclip"    },
            {0x800,      "sky"         },
            {0x1000,     "ainosight"   },
            {0x2000,     "clipshot"    },
            {0x4000,     "unknown_c4"  },
            {0x8000,     "unknown_c5"  },
            {0x10000,    "playerclip"  },
            {0x20000,    "monsterclip" },
            {0x40000,    "unknown_c6"  },
            {0x80000,    "unknown_c7"  },
            {0x100000,   "unknown_c8"  },
            {0x200000,   "unknown_c9"  },
            {0x400000,   "unknown_c10" },
            {0x800000,   "unknown_c11" },
            {0x1000000,  "interactible"},
            {0x2000000,  "unknown_c12" },
            {0x4000000,  "unknown_c13" },
            {0x8000000,  "detail"      },
            {0x10000000, "structural"  },
            {0x20000000, "unknown_c14" },
            {0x40000000, "unknown_c15" },
            {0x80000000, "nodrop"      },
        };

        const std::map<std::string, int> contentFlags_NameToFlag = {
            {"solid",        1         },
            {"foliage",      2         },
            {"unknown_c1",   4         },
            {"unknown_c2",   8         },
            {"transparent",  0x10      },
            {"water",        0x20      },
            {"canshootclip", 0x40      },
            {"clipmissile",  0x80      },
            {"unknown_c3",   0x100     },
            {"vehicleclip",  0x200     },
            {"itemclip",     0x400     },
            {"sky",          0x800     },
            {"ainosight",    0x1000    },
            {"clipshot",     0x2000    },
            {"unknown_c4",   0x4000    },
            {"unknown_c5",   0x8000    },
            {"playerclip",   0x10000   },
            {"monsterclip",  0x20000   },
            {"unknown_c6",   0x40000   },
            {"unknown_c7",   0x80000   },
            {"unknown_c8",   0x100000  },
            {"unknown_c9",   0x200000  },
            {"unknown_c10",  0x400000  },
            {"unknown_c11",  0x800000  },
            {"interactible", 0x1000000 },
            {"unknown_c12",  0x2000000 },
            {"unknown_c13",  0x4000000 },
            {"detail",       0x8000000 },
            {"structural",   0x10000000},
            {"unknown_c14",  0x20000000},
            {"unknown_c15",  0x40000000},
            {"nodrop",       0x80000000},
        };

        const std::map<int, std::string> surfaceFlags_FlagToName = {
            {1,          "nodamage"              },
            {2,          "slick"                 },
            {4,          "sky"                   },
            {8,          "ladder"                },
            {0x10,       "noimpact"              },
            {0x20,       "nomarks"               },
            {0x40,       "unknown_s1"            },
            {0x80,       "nodraw"                },
            {0x100,      "nopenetrate"           },
            {0x200,      "unknown_s2"            },
            {0x400,      "unknown_s3"            },
            {0x800,      "noreceivedynamicshadow"},
            {0x1000,     "caulk"                 },
            {0x2000,     "nosteps"               },
            {0x4000,     "nonsolid"              },
            {0x8000,     "arealight"             },
            {0x10000,    "unknown_s4"            },
            {0x20000,    "nodlight"              },
            {0x40000,    "nocastshadow"          },
            {0x80000,    "onlycastshadow"        },
            // 0x100000 - 0x2000000: material types
            {0x4000000,  "mantleon"              },
            {0x8000000,  "mantleover"            },
            {0x10000000, "mount"                 },
            {0x20000000, "unknown_s5"            },
            {0x40000000, "unknown_s6"            },
            {0x80000000, "portal"                },
        };

        const std::map<std::string, int> surfaceFlags_NameToFlag = {
            {"nodamage",               1         },
            {"slick",                  2         },
            {"sky",                    4         },
            {"ladder",                 8         },
            {"noimpact",               0x10      },
            {"nomarks",                0x20      },
            {"unknown_s1",             0x40      },
            {"nodraw",                 0x80      },
            {"nopenetrate",            0x100     },
            {"unknown_s2",             0x200     },
            {"unknown_s3",             0x400     },
            {"noreceivedynamicshadow", 0x800     },
            {"caulk",                  0x1000    },
            {"nosteps",                0x2000    },
            {"nonsolid",               0x4000    },
            {"arealight",              0x8000    },
            {"unknown_s4",             0x10000   },
            {"nodlight",               0x20000   },
            {"nocastshadow",           0x40000   },
            {"onlycastshadow",         0x80000   },
            // 0x100000 - 0x2000000: material types
            {"mantleon",               0x4000000 },
            {"mantleover",             0x8000000 },
            {"mount",                  0x10000000},
            {"unknown_s5",             0x20000000},
            {"unknown_s6",             0x40000000},
            {"portal",                 0x80000000},
        };

        const std::map<int, std::string> surfaceFlags_TypeToName = {
            {0x1,  "bark"        },
            {0x2,  "brick"       },
            {0x3,  "carpet"      },
            {0x4,  "cloth"       },
            {0x5,  "concrete"    },
            {0x6,  "dirt"        },
            {0x7,  "flesh"       },
            {0x8,  "foliage"     },
            {0x9,  "glass"       },
            {0x0A, "grass"       },
            {0x0B, "gravel"      },
            {0x0C, "ice"         },
            {0x0D, "metal"       },
            {0x0E, "mud"         },
            {0x0F, "paper"       },
            {0x10, "plaster"     },
            {0x11, "rock"        },
            {0x12, "sand"        },
            {0x13, "snow"        },
            {0x14, "water"       },
            {0x15, "wood"        },
            {0x16, "asphalt"     },
            {0x17, "ceramic"     },
            {0x18, "plastic"     },
            {0x19, "rubber"      },
            {0x1A, "cushion"     },
            {0x1B, "fruit"       },
            {0x1C, "paintedmetal"},
            {0x1D, "player"      },
            {0x1E, "tallgrass"   },
            {0x1F, "riotshield"  },
        };

        const std::map<std::string, int> surfaceFlags_NameToType = {
            {"bark",         0x1 },
            {"brick",        0x2 },
            {"carpet",       0x3 },
            {"cloth",        0x4 },
            {"concrete",     0x5 },
            {"dirt",         0x6 },
            {"flesh",        0x7 },
            {"foliage",      0x8 },
            {"glass",        0x9 },
            {"grass",        0xA },
            {"gravel",       0xB },
            {"ice",          0xC },
            {"metal",        0xD },
            {"mud",          0xE },
            {"paper",        0xF },
            {"plaster",      0x10},
            {"rock",         0x11},
            {"sand",         0x12},
            {"snow",         0x13},
            {"water",        0x14},
            {"wood",         0x15},
            {"asphalt",      0x16},
            {"ceramic",      0x17},
            {"plastic",      0x18},
            {"rubber",       0x19},
            {"cushion",      0x1A},
            {"fruit",        0x1B},
            {"paintedmetal", 0x1C},
            {"player",       0x1D},
            {"tallgrass",    0x1E},
            {"riotshield",   0x1F},
        };
    } // namespace BSPFlags
} // namespace T6
